### ISSUE TITLE
WS Server error, Julia 3.7, Fedora 21

### ISSUE THREAD

**Issue by TCMiranda** [JuliaWeb/WebSockets.jl#23] opened 2015-04-10 21:57 UTC
Please, i need some help to with the server.

I got the following message after run a copy from the example code from the docs.
Can' t fix it, dont know whats wrong..

```
WARNING: Dict-based `@docstring` config is deprecated. Use keywords instead.
Listening on 34440...

signal (11): Segmentation fault
unknown function (ip: -1728454171)
write at /usr/bin/../lib64/julia/sys.so (unknown line)
write at ./iobuffer.jl:235
Segmentation fault
```

I am running Julia v.3.7 with Fedora 21

Thanks!

**Comment by hustf** [comment] 2017-10-22 18:09
Much has changed since Julia 3.7. If you can reproduce with Julia 0.6, please include more information and we'll try to help. Closing this for now.

**Closed by hustf** 2017-10-22 18:09 UTC
